---
title: "Untitled"
output: github_document
---

# Problem 1

# create a data frame
library(tidyverse)

df1 = tibble(
  vec_numeric = rnorm(10),
  vec_char = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
  vec_logical = random_sample > 0,
  vec_factor = factor(c("A", "B", "C", "A", "B", "C", "A", "B", "C", "A")))   

df1

# take the mean of each variable
vec_numeric = rnorm(10)
vec_numeric_mean = mean(vec_numeric)

vec_char = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j")
vec_char_mean = mean(vec_char)

vec_logical = random_sample > 0
vec_logical_mean = vec_logical

vec_factor = factor(c("A", "B", "C", "A", "B", "C", "A", "B", "C", "A")
vec_factor_mean = mean(vec_factor)   

# it works for numeric vector but not for lofical vector, character vector, or factor vector

# convert logical vector to numeric, and multiply the random sample by the result
vec_logical_num = as.numeric(vec_logical)
l = vec_logical_num * random_sample

# convert logical vector to a factor, and multiply the random sample by the result
vec_logical_factor = as.factor(vec_logical)
f = vec_logical_factor * random_sample
# cannot multiply a factor vector to a numeric factor

# convert logical vector to a factor and then convert the result to numeric, and multiply the random sample by the result
vec_logical_factor_num = as.numeric(vec_logical_factor)
n = vec_logical_factor_num * random_sample


# Problem 2
data("penguins", package = "palmerpenguins")

nrow(penguins)
ncol(penguins)

flipper_length_mean = mean(penguins$flipper_length_mm, na.rm = TRUE)

# The data frame recorded information including species, island, bill length, bill depth, flipper length, body mass, and sex of 344 penguins from 2007 to 2009.
# Excluding missing records, the mean flipper length of penguins is 200.9152 mm.

ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()

ggsave("scatterplot 1.pdf")